on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  setup-postgresql:
    runs-on: ubuntu-latest
    steps:
      - name: Install PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install postgresql postgresql-contrib
          sudo service postgresql start
          sudo -u postgres psql -c "ALTER USER postgres PASSWORD '${{ secrets.POSTGRES_PASSWORD }}';"
      - name: Create Database and Table
        run: |
          sudo -u postgres psql -c "CREATE DATABASE cloudusers;"
          sudo -u postgres psql -c "CREATE TABLE IF NOT EXISTS users (id SERIAL PRIMARY KEY, firstname VARCHAR(255), lastname VARCHAR(255), email VARCHAR(255), password VARCHAR(255));"
      - name: Echo PostgreSQL setup completed
        run: echo "PostgreSQL setup completed"

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo PostgreSQL password
        run: echo ${{ secrets.POSTGRES_PASSWORD }}
      - name: Check Node.js and npm versions
        run: |
          node --version
          npm --version
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run tests
        env:
          POSTGRES_HOST: localhost
          POSTGRES_DB: cloudusers
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: POSTGRES_HOST=localhost POSTGRES_DB=cloudusers POSTGRES_USER=${{ secrets.POSTGRES_USER }} POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} npm run test
      - name: Echo Integration tests completed
        run: echo "Integration tests completed"
