name: Packer Build on PR Merge

on:
  push:
    branches:
      - main

jobs:
  packer_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        id: setup

      - name: Configure GCP Credentials
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: zip folder
        run: zip -r webapp-new.zip .

      - name: Run packer init
        run: packer init packer/templates/centos08.pkr.hcl

      - name: Run Packer Build
        id: packer_build
        run: |
          echo "Running Packer build"
          PACKER_OUTPUT=$(packer build -var "project_id=${{ secrets.GCP_PROJECT_ID }}" -var "zone=${{ secrets.GCP_ZONE }}" packer/templates/centos08.pkr.hcl)
          CUSTOM_IMAGE_ID=$(echo "$PACKER_OUTPUT" | grep -oP "custom-image-\d+")
          echo "Custom Image ID: $CUSTOM_IMAGE_ID"

          TIMESTAMP=$(date +"%d%H%M%S")
            gcloud config set project velvety-ground-414100
            gcloud compute instance-templates create webapp-${TIMESTAMP} \
                --project=velvety-ground-414100 \
                --instance-template-region=us-central1 \
                --machine-type=e2-medium \
                --region=us-central1 \
                --network=https://www.googleapis.com/compute/v1/projects/velvety-ground-414100/global/networks/terraform-gcp-vpc-0 \
                --subnet=https://www.googleapis.com/compute/v1/projects/velvety-ground-414100/regions/us-central1/subnetworks/webapp-subnet-0 \
                --create-disk=image=projects/velvety-ground-414100/global/images/$CUSTOM_IMAGE_ID,boot=yes,auto-delete=yes,device-name=persistent-disk-0,size=20,type=pd-balanced,kms-key=projects/velvety-ground-414100/locations/us-central1/keyRings/terraform-key-ring-test-v10/cryptoKeys/vm-crypto-key \
                --tags=webapp-subnet-0 \
                --metadata=startup-script='#!/bin/bash
                    cd /opt/csye6225

                    if [ -f .env ]; then
                        rm -f .env
                    fi

                    touch .env

                    key_value_exists() {
                        local key="$1"
                        local value="$2"
                        grep -q "^$key=" .env && grep -q "^$key=$value" .env
                    }

                    append_to_env() {
                        local key="$1"
                        local value="$2"
                        if ! key_value_exists "$key" "$value"; then
                            echo "$key=$value" >> .env
                        fi
                    }

                    append_to_env "POSTGRES_HOST" "10.58.0.2"
                    append_to_env "POSTGRES_DB" "${{secrets.DATABASE_NAME}}"
                    append_to_env "POSTGRES_USER" "${{secrets.DATABASE_USER_NAME}}"
                    append_to_env "POSTGRES_PASSWORD" "${{secrets.RANDOM_PASSWORD}}"

                    sudo systemctl daemon reload' \
                --service-account=terraform-user@velvety-ground-414100.iam.gserviceaccount.com \
                --scopes=https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/compute.readonly,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/pubsub,https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/userinfo.email \
                --reservation-affinity=any

            gcloud compute instance-groups managed set-instance-template regional-instance-group-manager --template=projects/velvety-ground-414100/regions/us-central1/instanceTemplates/webapp-${TIMESTAMP} --region=us-central1

            gcloud compute instance-groups managed rolling-action start-update regional-instance-group-manager --version=template=projects/velvety-ground-414100/regions/us-central1/instanceTemplates/webapp-${TIMESTAMP} --region=us-central1

            gcloud compute instance-groups managed wait-until regional-instance-group-manager --version-target-reached --region=us-central1
