name: Packer Build on PR Merge

on:
  push:
    branches:
      - main

jobs:
  packer_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        id: setup

      - name: Configure GCP Credentials
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: zip folder
        run: zip -r webapp.zip .
      - name: Run packer init
        run: packer init packer/templates/centos08.pkr.hcl

      - name: Run Packer Build
        id: packer_build
        run: |
          echo "Running Packer build"
          packer build packer/templates/centos08.pkr.hcl
