name: Packer CI Validation

on: [pull_request]

jobs:
  packer-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        id: setup

      - name: Run packer init
        run: packer init packer/centos08.pkr.hcl

      - name: Format Packer Template
        run: packer fmt -check=true packer/centos08.pkr.hcl

      - name: Validate Packer Template
        run: packer validate packer/centos08.pkr.hcl
